### PR TITLE
Created the README.md file with proper information in less lines

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
@SANTHOSH17-DOT Done with it sir

**Comment by SANTHOSH17-DOT** [comment]
Remove "Thanks for visiting"
Avoid paragraphs. Use points instead 
Use commands to explain file modes and other topics

**Comment by Bharadwajshivam28** [comment]
ok @SANTHOSH17-DOT

**Comment by Bharadwajshivam28** [comment]
can i set the lines points bys

**Comment by Bharadwajshivam28** [comment]
sir i dont have much knoweldege of command that is used to explain file modes so can you give any reference @SANTHOSH17-DOT

**Comment by Bharadwajshivam28** [comment]
currently i have removed para and structured them in point @SANTHOSH17-DOT

**Comment by Bharadwajshivam28** [comment]
but can you explain about commands for file modes

**Pull request closed without merging**
