### PR TITLE
Important keywords and Emojis added to Readme.md

### PR DESCRIPTION
**Pull request by GitWiz01**
Added some emojis to make it more interactive and fun. Hope you like it

### CODE REVIEW

**Review by Shiv10122003 — APPROVED** [review]
Great initiative, Improved the readme file a lot.

**Comment by SANTHOSH17-DOT** [comment]
@GitWiz01 Emojis seem redundant. Please remove it. You may contribute by fixing the typos if you find any.

**Comment by GitWiz01** [comment]
> @GitWiz01 Emojis seem redundant. Please remove it. You may contribute by fixing the typos if you find any.

ok I will remove them

**Comment by GitWiz01** [comment]
I have updated the readme without emoji and had already fixed the typos before. please suggest if anything needs to be changed.

**Comment by SANTHOSH17-DOT** [comment]
There's a merge conflict. Kindly resolve it and squash your eight commits into a single commit

**Pull request closed without merging**
