### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by GitWiz01**

### CODE REVIEW

**Comment by GitWiz01** [comment]
please review it @SANTHOSH17-DOT

**Review by SANTHOSH17-DOT — COMMENTED** [review]
Please grammar check the fun fact

**Comment by GitWiz01** [comment]
@SANTHOSH17-DOT  Sir I have done the Grammar check. Please add the IWOC and the difficulty level tag if this now good to merge.

**Comment by SANTHOSH17-DOT** [comment]
Squash your commits into a single commit

**Comment by GitWiz01** [comment]
@SANTHOSH17-DOT done sir

**Comment by GitWiz01** [comment]
@SANTHOSH17-DOT sir please check the pr.

**Comment by SANTHOSH17-DOT** [comment]
This is under JWOC right?

**Comment by GitWiz01** [comment]
@SANTHOSH17-DOT No sir It is under IWOC'23

**Comment by SANTHOSH17-DOT** [comment]
Okay. I'm giving IWOC easy badge

**Comment by SANTHOSH17-DOT** [comment]
Thank you for your contribution.

**Comment by GitWiz01** [comment]
Thank you @SANTHOSH17-DOT

**Pull request merged**
