### PR TITLE
CSRF added and updated

### PR DESCRIPTION
**Pull request by White-rose69**
@SANTHOSH17-DOT this is the new PR request for CSRF issue.

### CODE REVIEW

**Comment by White-rose69** [comment]
No changes were made in the CSRF folder, only the IDOR files were deleted.

**Comment by White-rose69** [comment]
??

**Comment by White-rose69** [comment]
@SANTHOSH17-DOT there're only 2 days left until the phase 1 ends can you please review this PR.
Thanks

**Comment by SANTHOSH17-DOT** [comment]
@White-rose69 Documentation looks fine. I'm sorry about the delay. I'm merging your pr now.

**Comment by SANTHOSH17-DOT** [comment]
closes #64

**Pull request merged**
