### PR TITLE
Update readme file

### PR DESCRIPTION
**Pull request by Suryansh1720001**
Referring the Issue - #53 

Hello @SANTHOSH17-DOT 

### Features that I added

- Contributors details
- Project admin details
- Add the contributing line with a guideline link so that everyone motivates by that.
- Center heading for more attractive
- footer in the readme file

Kindly check this and merge it accordingly with IWOC all labels.

### CODE REVIEW

**Comment by SANTHOSH17-DOT** [comment]
Looks good. Could you squash all your commits into a single commit? I appreciate your contribution. I'm giving an easy label since it's an easier issue. @Suryansh1720001

**Comment by Suryansh1720001** [comment]
@SANTHOSH17-DOT 
Thank you. 
But I think the squash thing will be done from the admin side at the time of merging the code. You can do that very simply with just one click.
Let me show you - 
## - **from this dropdown, you can open and select the squash option** 
-
image


## - **Now after selecting this - Write your commit line for this purpose (Like - the Readme file updated) and then you can merge it by simple one command.**

image

**Comment by Suryansh1720001** [comment]
@SANTHOSH17-DOT 
Now after understanding this you can merge by code and give the IWOC labels in ISSUE #53 side also. So that it will be counted under IWOC.

- Give the IWOC labels ( IWOC and easy/medium) in ISSUE #53 side and also do this thing here also. It is necessary so that it will be counted under IWOC.

**Review by SANTHOSH17-DOT — APPROVED** [review]

**Comment by SANTHOSH17-DOT** [comment]
@Suryansh1720001 Thank you for letting me know about this. I thought I will become the commit author when I squash and merge.

**Comment by Suryansh1720001** [comment]
@SANTHOSH17-DOT 
There's no need to worry, the world of open-source presents ample opportunities for learning.

**Pull request merged**
