### PR TITLE
Completd

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
Completed sir

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
@SANTHOSH17-DOT  Done

**Comment by SANTHOSH17-DOT** [comment]
Webpage is not needed. I asked you leave it in shell shock because you've done that already. Just markdown is sufficient

**Comment by SANTHOSH17-DOT** [comment]
Kindly use meaningful PR titles

**Comment by Bharadwajshivam28** [comment]
ok

**Comment by Bharadwajshivam28** [comment]
@SANTHOSH17-DOT  So  sir in TCP, setuid and buffer webpage is not needed just README IS NEEDED?

**Comment by SANTHOSH17-DOT** [comment]
Yes

**Comment by Bharadwajshivam28** [comment]
like you have assigned me the  buffer and setuid also

**Comment by SANTHOSH17-DOT** [comment]
Yes.

**Comment by Bharadwajshivam28** [comment]
ok sir @SANTHOSH17-DOT

**Comment by Bharadwajshivam28** [comment]
Just correcting it

**Pull request closed without merging**
