### PR TITLE
XSS added

### PR DESCRIPTION
**Pull request by White-rose69**
@SANTHOSH17-DOT please review my PR and merge it

### CODE REVIEW

**Comment by SANTHOSH17-DOT** [comment]
@White-rose69 I'll review it ASAP

**Comment by White-rose69** [comment]
Is there an issue in my PR???
And when will I be assigned with the new issue that I raised??

**Comment by SANTHOSH17-DOT** [comment]
@White-rose69 documentation looks great. But the lab link isn't working. Could you look into this?

**Comment by White-rose69** [comment]
@SANTHOSH17-DOT I have updated the README file and the lab link is working now.
And making an HTML page with XSS vulnerability in it is a difficult task for me as I don't know Web Development that much,
that is why I asked you beforehand if I could use a lab or not.

**Comment by White-rose69** [comment]
@SANTHOSH17-DOT can you review it please

**Comment by SANTHOSH17-DOT** [comment]
Link isn't active again. I'm getting this
"Server Error: Gateway Timeout (0) connecting to 0a4d00f7039648d6c0e6cce800ae0070.web-security-academy.net"

**Comment by White-rose69** [comment]
Updated.

**Comment by White-rose69** [comment]
??

**Comment by SANTHOSH17-DOT** [comment]
Looks cool. Sorry I didn't get the notification. I'll merge it now

**Review by SANTHOSH17-DOT — APPROVED** [review]

**Comment by SANTHOSH17-DOT** [comment]
Closed #55

**Comment by White-rose69** [comment]
@SANTHOSH17-DOT I did not got the points for this PR.
Please assign this PR with the relevant labels

**Pull request merged**
