### PR TITLE
Added files for Keylogger made in python

### PR DESCRIPTION
**Pull request by SukarayamJanjua**

### CODE REVIEW

**Comment by SukarayamJanjua** [comment]
@SANTHOSH17-DOT I've added the files.kindly have a look and merge my PR !!😊...

**Comment by SANTHOSH17-DOT** [comment]
Give more clarity to the second point in the readme.
Also add screenshots of the demo

**Comment by SANTHOSH17-DOT** [comment]
image
image
I am getting this error. Please fix it

**Comment by SukarayamJanjua** [comment]
Oh...le'me see ...I'll make another commit just in few minutes

**Comment by SukarayamJanjua** [comment]
Hey!!@SANTHOSH17-DOT I've fixed the issue and even updated readme file with proper explanation and screenshots to refer...hope it goes all good now !!

**Comment by SukarayamJanjua** [comment]
@SANTHOSH17-DOT brother I just noticed this pull request isn't having hacktoberfest label...kindly add that as well 😊!!

**Comment by SANTHOSH17-DOT** [comment]
image
Can you make the readme prettier?
Check readme.so

**Comment by SukarayamJanjua** [comment]
@SANTHOSH17-DOT I've done that...and i think it wont be possible now to rename the folder to uppercase once its commited on github !!

**Comment by SANTHOSH17-DOT** [comment]
That's fine. Squash all your commits into one commit

**Comment by SukarayamJanjua** [comment]
@SANTHOSH17-DOT hey actually I'm unable to squash them because I commited files from 2-3 different locations. kindly merge all these and if possible from your side you may squash them..I dont have any clue regarding this

**Comment by SANTHOSH17-DOT** [comment]
Did you try git reset command with soft flag?

**Comment by SukarayamJanjua** [comment]
@SANTHOSH17-DOT So what should be done now...?

**Comment by SANTHOSH17-DOT** [comment]
There are a lot of redundant commits. So try to squash it

**Comment by SANTHOSH17-DOT** [comment]
Use this command
git reset --soft HEAD~9
git commit -m "<message>"

**Comment by SukarayamJanjua** [comment]
okay will try these 👍

**Comment by SukarayamJanjua** [comment]
@SANTHOSH17-DOT brother I;m unable to do it mainly because I had commited from different locations so what I'll be doing is ..I'll close this PR and make a new PR where I'll commit all files at once you can add hacktoberfest lable to it and then merge it as contribution...I hope this will be fine? so shall I close this PR now?

**Pull request closed without merging**
