### PR TITLE
I Created an Shell Shock Attack Documentation Webpage 

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
Please check it and If you find it valueable then merge it .

### CODE REVIEW

**Comment by Bharadwajshivam28** [comment]
@SANTHOSH17-DOT  Please review and merge it

**Comment by Bharadwajshivam28** [comment]
Or if there is some changes possible then please let me know it to me @SANTHOSH17-DOT

**Comment by SANTHOSH17-DOT** [comment]
I'll go through this webpage. But it would be great if you can simulate this attack in an environment with bash version 1.0.3–4.3. You may go with a docker container.

**Comment by SANTHOSH17-DOT** [comment]
Also go through the contributing.md file. 
[Good commit message](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)

**Comment by Bharadwajshivam28** [comment]
@SANTHOSH17-DOT  Ya ok I will work on your comments and make it Done as required by you

**Comment by Bharadwajshivam28** [comment]
> Also go through the contributing.md file. [Good commit message](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)

ya ok @SANTHOSH17-DOT

**Comment by Bharadwajshivam28** [comment]
will work on these @SANTHOSH17-DOT

**Comment by Bharadwajshivam28** [comment]
> I'll go through this webpage. But it would be great if you can simulate this attack in an environment with bash version 1.0.3–4.3. You may go with a docker container. Take this [video](https://youtu.be/aCj-Khvg5n0as) a reference and give them credits

Sir can you explain this to me in simple language like i am beginner in Open source. What to do next in this like in simple language @SANTHOSH17-DOT

**Comment by SANTHOSH17-DOT** [comment]
This needs knowledge of docker and Linux systems.

**Comment by Bharadwajshivam28** [comment]
@SANTHOSH17-DOT  ok sir i have not knowledge of docker .

**Comment by Bharadwajshivam28** [comment]
@SANTHOSH17-DOT OK i will make a markdown page instead of this webpage

**Comment by Bharadwajshivam28** [comment]
@SANTHOSH17-DOT  should i delete that html file or simply add the markdown file without deleting html file

**Comment by SANTHOSH17-DOT** [comment]
Let it be

**Comment by Bharadwajshivam28** [comment]
ok @SANTHOSH17-DOT

**Pull request closed without merging**
