### PR TITLE
Shell shock

### PR DESCRIPTION
**Pull request by Bharadwajshivam28**
Done with it @SANTHOSH17-DOT

### CODE REVIEW

**Comment by SANTHOSH17-DOT** [comment]
Change the file name from index.md to README.md

**Comment by Bharadwajshivam28** [comment]
ok

**Comment by Bharadwajshivam28** [comment]
@SANTHOSH17-DOT  Done sir

**Comment by Bharadwajshivam28** [comment]
I made the README.md good and tidy by giving space between every line ending

**Comment by Bharadwajshivam28** [comment]
@SANTHOSH17-DOT 
 Hello sir any response

**Comment by SANTHOSH17-DOT** [comment]
Use quotes if there's any code being used in the readme. Similarly for file path. 
The primary notion of this project is to simulate and research an attack vector. So, could you make the content more concise?

**Comment by Bharadwajshivam28** [comment]
ok @SANTHOSH17-DOT

**Comment by Bharadwajshivam28** [comment]
like can you explain me in simple words like what should be the next step @SANTHOSH17-DOT

**Comment by Bharadwajshivam28** [comment]
like i am new in Open Source so

**Comment by SANTHOSH17-DOT** [comment]
> ok @SANTHOSH17-DOT 

Can u make the readme concise?

**Comment by Bharadwajshivam28** [comment]
ok @SANTHOSH17-DOT

**Comment by Bharadwajshivam28** [comment]
like the readme should be more informative but in less lines

**Comment by SANTHOSH17-DOT** [comment]
Yes

**Comment by Bharadwajshivam28** [comment]
@SANTHOSH17-DOT Done made the README.md more informative and also in less lines

**Comment by SANTHOSH17-DOT** [comment]
Good job

**Comment by Bharadwajshivam28** [comment]
thanks @SANTHOSH17-DOT

**Pull request merged**
